import { Geist, Geist_Mono,JetBrains_Mono  } from "next/font/google";
import "./globals.css";

// components
import Header from "@/components/ui/Header";
import PageTransition from "@/components/ui/PageTransition";
import StairTransition from "@/components/ui/StairTransition";


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});
const jetbrainsMono = JetBrains_Mono({
  variable: "--font-jetbrains-mono",
  subsets: ["latin"],
  display: "swap", 
  weight :['100','200','300','400','500','600','700','800']
});


export const metadata = {
  title: "Shamily's Profile",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${jetbrainsMono.variable} antialiased`}
      >
        <Header/>
        <StairTransition/>
        <PageTransition>{children}</PageTransition>
       
      </body>
    </html>
  );
}
